# Generated by Django 5.0.6 on 2024-06-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0005_rename_funiture_provider_property_furniture_provider'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rental_agreement_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('actual_rent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rental_agreement_starting_date', models.DateField(null=True)),
                ('rental_agreement_ending_date', models.DateField(null=True)),
                ('rental_agreement_notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.property')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='tenants.tenant')),
                ('tenant_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_2', to='tenants.tenant')),
            ],
        ),
    ]
