# Generated by Django 5.0.6 on 2024-06-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renalagreement',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
