# Generated by Django 5.0.6 on 2024-06-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0002_alter_renalagreement_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renalagreement',
            old_name='active',
            new_name='is_active',
        ),
    ]
