# Generated by Django 5.0.6 on 2024-06-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0003_rename_active_renalagreement_is_active'),
        ('properties', '0005_rename_funiture_provider_property_furniture_provider'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RenalAgreement',
            new_name='RentalAgreement',
        ),
    ]
