# Generated by Django 5.0.6 on 2024-06-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0004_rename_renalagreement_rentalagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='security_deposits',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
