# Generated by Django 5.0.6 on 2024-06-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0006_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='actual_rent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_actual_rent', to='ltrentals.rentalagreement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_tenant', to='ltrentals.rentalagreement'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='tenant_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_tenant_2', to='ltrentals.rentalagreement'),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_property', to='ltrentals.rentalagreement'),
        ),
    ]
