# Generated by Django 5.0.6 on 2024-06-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0007_monthlypayment_actual_rent_monthlypayment_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='actual_rent',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='tenant_2',
        ),
    ]
