# Generated by Django 5.0.6 on 2024-06-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0008_remove_monthlypayment_actual_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='months_due',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='paid_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='payment_mehtod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('PIR', 'Pir')], default='PIR', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='pid_month',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='total_months',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='actual_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
