# Generated by Django 5.0.6 on 2024-06-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0009_monthlypayment_months_due_monthlypayment_paid_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='months_due',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='total_months',
        ),
    ]
