# Generated by Django 5.0.6 on 2024-06-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0010_remove_monthlypayment_months_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='paid_year',
        ),
    ]
