# Generated by Django 5.0.6 on 2024-06-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0011_remove_monthlypayment_paid_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='property',
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='rental_agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreement', to='ltrentals.rentalagreement'),
        ),
    ]
