# Generated by Django 5.0.6 on 2024-06-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0012_remove_monthlypayment_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='pid_month',
            new_name='paid_month',
        ),
    ]
