# Generated by Django 5.0.6 on 2024-06-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0013_rename_pid_month_monthlypayment_paid_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='rental_agreement',
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ltrentals.monthlypayment'),
        ),
    ]
