# Generated by Django 5.0.6 on 2024-06-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0014_remove_monthlypayment_rental_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalagreement',
            name='payments',
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='rental_agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreement', to='ltrentals.rentalagreement'),
        ),
    ]
