# Generated by Django 5.0.6 on 2024-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0015_remove_rentalagreement_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='total_months',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
