# Generated by Django 5.0.6 on 2024-06-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0016_rentalagreement_total_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='months_paid',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
