# Generated by Django 5.0.6 on 2024-06-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0017_rentalagreement_months_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='months_remaining',
            field=models.PositiveSmallIntegerField(default=32),
            preserve_default=False,
        ),
    ]
