# Generated by Django 5.0.6 on 2024-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0018_rentalagreement_months_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='months_owed',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
