# Generated by Django 5.0.6 on 2024-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0019_rentalagreement_months_owed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='months_owed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='months_paid',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='months_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='total_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
