# Generated by Django 5.0.6 on 2024-06-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0020_alter_rentalagreement_months_owed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='expiring',
            field=models.BooleanField(default=False),
        ),
    ]
