# Generated by Django 5.0.6 on 2024-06-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltrentals', '0021_rentalagreement_expiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='months_owed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
