# Generated by Django 5.0.6 on 2024-06-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('phone_2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_id', models.PositiveIntegerField(unique=True)),
                ('tax_office', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(choices=[('id_card', 'Id Card'), ('passport', 'Passport')], max_length=30)),
                ('id_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(choices=[('GR', 'GR'), ('UK', 'UK')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('legal_action', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
