# Generated by Django 5.0.6 on 2024-06-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('tax_id', models.PositiveIntegerField(unique=True)),
                ('tax_office', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(choices=[('ID', 'Id'), ('Passport', 'Passport')], max_length=30)),
                ('id_number', models.CharField(max_length=50)),
            ],
        ),
    ]
