# Generated by Django 5.0.6 on 2024-06-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantModel',
            new_name='Tenant',
        ),
    ]
