# Generated by Django 5.0.6 on 2024-06-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rename_tenantmodel_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_type',
            field=models.CharField(choices=[('Id Card', 'Id'), ('Passport', 'Passport')], max_length=30),
        ),
    ]
