# Generated by Django 5.0.6 on 2024-06-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_email_tenant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
