# Generated by Django 5.0.6 on 2024-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenant_is_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
