# Generated by Django 5.0.6 on 2024-06-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
