# Generated by Django 5.0.6 on 2024-06-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_phone_alter_tenant_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
