# Generated by Django 5.0.6 on 2024-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_tenant_fathers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_type',
            field=models.CharField(choices=[('id_card', 'Id Card'), ('passport', 'Passport')], max_length=30),
        ),
    ]
