# Generated by Django 5.0.6 on 2024-06-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_tenant_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
