# Generated by Django 5.0.6 on 2024-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_alter_tenant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_type',
            field=models.CharField(choices=[('id_card', 'Id Card'), ('passport', 'Passport')], default='Choose', max_length=30),
        ),
    ]
