# Generated by Django 5.0.6 on 2024-06-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_tenant_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(choices=[('Greek', 'GR'), ('British', 'UK')], default='changeme', max_length=50),
            preserve_default=False,
        ),
    ]
