# Generated by Django 5.0.6 on 2024-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(choices=[('GR', 'Greek'), ('UK', 'British')], max_length=50),
        ),
    ]
