# Generated by Django 5.0.6 on 2024-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_alter_tenant_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(choices=[('GR', 'GR'), ('UK', 'UK')], max_length=50),
        ),
    ]
