# Generated by Django 5.0.6 on 2024-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_alter_tenant_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_2',
            field=models.IntegerField(blank=True),
        ),
    ]
