# Generated by Django 5.0.6 on 2024-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_alter_tenant_phone_alter_tenant_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
