# Generated by Django 5.0.6 on 2024-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_alter_tenant_phone_alter_tenant_phone_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
