# Generated by Django 5.0.6 on 2024-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_tenant_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
