# Generated by Django 5.0.6 on 2024-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_alter_tenant_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='legal_action',
            field=models.BooleanField(default=False),
        ),
    ]
