# Generated by Django 5.0.6 on 2024-06-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=2)),
                ('file_number', models.PositiveSmallIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_2', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_id', models.PositiveIntegerField(unique=True)),
                ('tax_office', models.CharField(blank=True, max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry_date', models.DateField()),
                ('nationality', models.CharField(choices=[('CN', 'CN'), ('GR', 'GR'), ('UK', 'UK')], max_length=50)),
                ('cooperation_type', models.CharField(choices=[('FULL', 'FULL'), ('ONLY PR', 'ONLY PR'), ('ONLY MANAGEMENT', 'ONLY MANAGEMENT'), ('NONE', 'NONE')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_team', to='collaborators.legal')),
            ],
        ),
    ]
