# Generated by Django 5.0.6 on 2024-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_id', models.PositiveIntegerField(unique=True)),
                ('tax_office', models.CharField(blank=True, max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('nationality', models.CharField(choices=[('CN', 'Chinese'), ('GR', 'Greek'), ('UK', 'British')], max_length=50)),
            ],
        ),
    ]
