# Generated by Django 5.0.6 on 2024-06-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='file_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
