# Generated by Django 5.0.6 on 2024-06-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0003_alter_legal_company_name'),
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='law_firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_team', to='collaborators.legal'),
        ),
    ]
