# Generated by Django 5.0.6 on 2024-06-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_alter_landlord_law_firm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='law_firm',
        ),
    ]
