# Generated by Django 5.0.6 on 2024-06-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_landlord_file_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='file_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
