# Generated by Django 5.0.6 on 2024-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0003_alter_landlord_file_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='file_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
