# Generated by Django 5.0.6 on 2024-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0003_remove_landlord_law_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='law_firm',
            field=models.CharField(choices=[('K/P', 'K/P'), ('KMD', 'KMD')], default='whatever', max_length=50),
            preserve_default=False,
        ),
    ]
