# Generated by Django 5.0.6 on 2024-06-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0004_alter_landlord_file_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='file_type',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], default='F', max_length=2),
            preserve_default=False,
        ),
    ]
