# Generated by Django 5.0.6 on 2024-06-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0004_landlord_law_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='law_firm',
            field=models.CharField(choices=[('K/P', 'K/P'), ('KMD', 'KMD')], max_length=50, null=True),
        ),
    ]
