# Generated by Django 5.0.6 on 2024-06-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0005_landlord_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='file_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
