# Generated by Django 5.0.6 on 2024-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0006_alter_landlord_file_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='nationality',
            field=models.CharField(choices=[('CN', 'CN'), ('GR', 'GR'), ('UK', 'UK')], max_length=50),
        ),
    ]
