# Generated by Django 5.0.6 on 2024-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0007_alter_landlord_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='phone_2',
            field=models.IntegerField(blank=True),
        ),
    ]
