# Generated by Django 5.0.6 on 2024-06-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0008_alter_landlord_phone_alter_landlord_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='phone_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
