# Generated by Django 5.0.6 on 2024-06-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0009_alter_landlord_phone_alter_landlord_phone_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='cooperation_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('ONLY PR', 'ONLY PR'), ('ONLY MANAGEMENT', 'ONLY MANAGEMENT')], default='FULL', max_length=50),
            preserve_default=False,
        ),
    ]
