# Generated by Django 5.0.6 on 2024-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0010_landlord_cooperation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='cooperation_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('ONLY PR', 'ONLY PR'), ('ONLY MANAGEMENT', 'ONLY MANAGEMENT'), ('NONE', 'NONE')], max_length=50),
        ),
    ]
