# Generated by Django 5.0.6 on 2024-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0011_alter_landlord_cooperation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
