# Generated by Django 5.0.6 on 2024-06-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0012_landlord_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='law_firm',
            field=models.CharField(choices=[('K/P', 'K/P'), ('KMD', 'KMD')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
