# Generated by Django 5.0.6 on 2024-06-01 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, max_length=50)),
                ('manager_phone', models.CharField(blank=True, max_length=25)),
                ('manager_email', models.EmailField(blank=True, max_length=50)),
                ('manager_bank_name', models.CharField(blank=True, max_length=25)),
                ('manager_iban', models.CharField(blank=True, max_length=25)),
                ('manager_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_id', models.PositiveIntegerField(unique=True)),
                ('buying_contract_date', models.DateField()),
                ('selling_contract_date', models.DateField()),
                ('works_needed', models.BooleanField(default=False)),
                ('works_progress', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started Yet', 'Not Started Yet')], default='Completed', max_length=50)),
                ('works_notes', models.TextField(blank=True)),
                ('furniture_needed', models.CharField(choices=[('Fully furnished', 'Full'), ('Semi - furnished', 'Partial'), ('No Furniture', 'No Furniture')], default='Fully furnished', max_length=50)),
                ('furniture_progress', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started Yet', 'Not Started Yet')], default='Not Started Yet', max_length=50)),
                ('furniture_notes', models.TextField(blank=True)),
                ('utilisation', models.CharField(choices=[('Long-Term Rental', 'Long Term'), ('Short-Term Rental', 'Short Term'), ('Managed - Not For Rent', 'Managed Closed'), ('Managed - Ownership Occupancy', 'Managed Ownership Occupancy'), ('Not Managed', 'No Management')], max_length=50)),
                ('utilisation_status', models.CharField(choices=[('Rented', 'Rented'), ('Vacant', 'Vacant'), ('Remove From Market', 'Remove')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=50)),
                ('zip_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('floor', models.SmallIntegerField()),
                ('apartment_no', models.CharField(max_length=10)),
                ('under_rg', models.BooleanField(default=True)),
                ('rg_ammount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rg_percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('rg_starting', models.DateField()),
                ('rg_ending', models.DateField()),
                ('management_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_rent', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProperyUtilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_registry_no', models.CharField(blank=True, max_length=20)),
                ('water_meter', models.CharField(blank=True, max_length=20)),
                ('water_username', models.CharField(blank=True, max_length=50)),
                ('water_password', models.CharField(blank=True, max_length=50)),
                ('electricity_provider', models.CharField(blank=True, max_length=50)),
                ('electricity_utility_no', models.CharField(blank=True, max_length=20)),
                ('electricity_meter', models.CharField(blank=True, max_length=20)),
                ('electricity_username', models.CharField(blank=True, max_length=50)),
                ('electricity_password', models.CharField(blank=True, max_length=50)),
                ('lng_provider', models.CharField(blank=True, max_length=50)),
                ('lng_utility_no', models.CharField(blank=True, max_length=50)),
                ('lng_meter', models.CharField(blank=True, max_length=50)),
                ('lng_username', models.CharField(blank=True, max_length=50)),
                ('lng_password', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
