# Generated by Django 5.0.6 on 2024-06-07 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborators', '0001_initial'),
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBuildingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, max_length=50)),
                ('manager_phone', models.CharField(blank=True, max_length=25)),
                ('manager_email', models.EmailField(blank=True, max_length=50)),
                ('manager_bank_name', models.CharField(blank=True, max_length=25)),
                ('manager_iban', models.CharField(blank=True, max_length=25)),
                ('manager_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_id', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=50)),
                ('zip_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('floor', models.SmallIntegerField()),
                ('apartment_no', models.CharField(max_length=10)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_contract_date', models.DateField()),
                ('selling_contract_date', models.DateField()),
                ('works_progress', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started Yet', 'Not Started Yet')], default='Completed', max_length=50)),
                ('works_notes', models.TextField(blank=True)),
                ('furniture_needed', models.CharField(choices=[('Fully furnished', 'Full'), ('Semi - furnished', 'Partial'), ('No Furniture', 'No Furniture')], default='Fully furnished', max_length=50)),
                ('furniture_progress', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Started Yet', 'Not Started Yet')], default='Not Started Yet', max_length=50)),
                ('furniture_notes', models.TextField(blank=True)),
                ('utilisation', models.CharField(choices=[('Not Decided Yet', 'Undecided'), ('Long-Term Rental', 'Long Term'), ('Short-Term Rental', 'Short Term'), ('Managed - Not For Rent', 'Managed Closed'), ('Managed - Ownership Occupancy', 'Managed Ownership Occupancy'), ('Not Managed', 'No Management')], max_length=50)),
                ('utilisation_status', models.CharField(blank=True, choices=[('None', 'None'), ('Rented', 'Rented'), ('Vacant', 'Vacant'), ('Remove From Market', 'Remove From Market')], max_length=50)),
                ('under_rental_guarantee', models.BooleanField(default=False, null=True)),
                ('rg_ammount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('rg_percentage', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('rg_starting', models.DateField(null=True)),
                ('rg_ending', models.DateField(null=True)),
                ('management_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('water_registry_no', models.CharField(blank=True, max_length=20)),
                ('water_meter', models.CharField(blank=True, max_length=20)),
                ('water_username', models.CharField(blank=True, max_length=50)),
                ('water_password', models.CharField(blank=True, max_length=50)),
                ('electricity_utility_no', models.CharField(blank=True, max_length=20)),
                ('electricity_meter', models.CharField(blank=True, max_length=20)),
                ('electricity_username', models.CharField(blank=True, max_length=50)),
                ('electricity_password', models.CharField(blank=True, max_length=50)),
                ('lng_utility_no', models.CharField(blank=True, max_length=50)),
                ('lng_meter', models.CharField(blank=True, max_length=50)),
                ('lng_username', models.CharField(blank=True, max_length=50)),
                ('lng_password', models.CharField(blank=True, max_length=50)),
                ('electricity_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electricity', to='collaborators.electricity')),
                ('lng_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='natural_gas', to='collaborators.naturalgas')),
                ('owner_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_owner_1', to='landlords.landlord')),
                ('owner_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_owner_2', to='landlords.landlord')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
