# Generated by Django 5.0.6 on 2024-06-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyModel',
            new_name='Property',
        ),
    ]
