# Generated by Django 5.0.6 on 2024-06-07 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_furnitureprovider_subcontractor'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='funiture_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='furniture_provider', to='collaborators.furnitureprovider'),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_contractor', to='collaborators.subcontractor'),
        ),
    ]
