# Generated by Django 5.0.6 on 2024-06-06 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rental_guarantee',
        ),
        migrations.AddField(
            model_name='property',
            name='rg_ammount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rg_ending',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rg_percentage',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='property',
            name='rg_starting',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='under_rental_guarantee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='PropertyRentalGuarantee',
        ),
    ]
