# Generated by Django 5.0.6 on 2024-06-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_propertymodel_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyManagerModel',
            new_name='PropertyManager',
        ),
        migrations.RenameModel(
            old_name='ProperyUtilityModel',
            new_name='ProperyUtility',
        ),
    ]
