# Generated by Django 5.0.6 on 2024-06-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_alter_buildingmanagementcompany_company_name_and_more'),
        ('properties', '0002_property_sub_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='electricity_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='electricity', to='collaborators.electricity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='lng_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='natural_gas', to='collaborators.naturalgas'),
            preserve_default=False,
        ),
    ]
