# Generated by Django 5.0.6 on 2024-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_funiture_provider_property_sub_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='constructed_by',
            field=models.CharField(choices=[('Us', 'Us'), ('Not Us', 'Not Us')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
