# Generated by Django 5.0.6 on 2024-06-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_propertymanagermodel_propertymanager_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyManager',
            new_name='PropertyBuildingManager',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='surface',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
