# Generated by Django 5.0.6 on 2024-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_electricity_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_manager_phone',
            field=models.IntegerField(null=True),
        ),
    ]
