# Generated by Django 5.0.6 on 2024-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_constructed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_manager_apt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='building_manager_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='building_manager_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='building_manager_phone',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
