# Generated by Django 5.0.6 on 2024-06-08 07:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0005_rename_buildingmanagerindividual_buildingmanagementcompany'),
        ('landlords', '0001_initial'),
        ('properties', '0004_property_building_manager_apt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='funiture_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furniture_provider', to='collaborators.furnitureprovider'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_owner_1', to='landlords.landlord'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_owner_2', to='landlords.landlord'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rg_ammount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rg_ending',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rg_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='rg_starting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sub_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_contractor', to='collaborators.subcontractor'),
        ),
    ]
