# Generated by Django 5.0.6 on 2024-06-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_building_manager_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='funiture_provider',
            new_name='furniture_provider',
        ),
    ]
