# Generated by Django 5.0.6 on 2024-06-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_propertymanager_propertybuildingmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='under_rg',
            field=models.BooleanField(default=False),
        ),
    ]
