# Generated by Django 5.0.6 on 2024-06-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_funiture_provider_property_furniture_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='utilisation_status',
            field=models.CharField(blank=True, choices=[('Rented', 'Rented'), ('Vacant', 'Vacant'), ('Remove From Market', 'Remove From Market')], default='Vacant', max_length=50),
        ),
    ]
