# Generated by Django 5.0.6 on 2024-06-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_under_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='utilisation_status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Vacant', 'Vacant'), ('Remove From Market', 'Remove From Market')], max_length=50),
        ),
    ]
