# Generated by Django 5.0.6 on 2024-06-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_utilisation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_manager_phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
