# Generated by Django 5.0.6 on 2024-06-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_utilisation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='works_needed',
        ),
    ]
