# Generated by Django 5.0.6 on 2024-06-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_property_works_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='actual_rent',
        ),
    ]
