# Generated by Django 5.0.6 on 2024-06-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_building_manager_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gr_expiring',
            field=models.BooleanField(default=False),
        ),
    ]
