# Generated by Django 5.0.6 on 2024-06-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_gr_expiring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='gr_expiring',
            new_name='rg_expiring',
        ),
    ]
