# Generated by Django 5.0.6 on 2024-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0013_landlord_law_firm'),
        ('properties', '0008_remove_property_actual_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='under_rg',
            new_name='under_rental_guarantee',
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ManyToManyField(related_name='property', to='landlords.landlord'),
        ),
    ]
