# Generated by Django 5.0.6 on 2024-06-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_rename_gr_expiring_property_rg_expiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_manager_phone',
            field=models.IntegerField(null=True),
        ),
    ]
