# Generated by Django 5.0.6 on 2024-06-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_property_owner_property_owner_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_2',
        ),
    ]
