# Generated by Django 5.0.6 on 2024-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_building_manager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_manager_phone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
