# Generated by Django 5.0.6 on 2024-06-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0013_landlord_law_firm'),
        ('properties', '0011_remove_property_owner_1_remove_property_owner_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='property_owner_1', to='landlords.landlord'),
        ),
    ]
