# Generated by Django 5.0.6 on 2024-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_property_building_manager_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyBuildingManager',
        ),
        migrations.AddField(
            model_name='property',
            name='building_manager_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='building_manager_iban',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
