# Generated by Django 5.0.6 on 2024-06-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0013_landlord_law_firm'),
        ('properties', '0013_alter_property_owner_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_owner_1', to='landlords.landlord'),
        ),
    ]
