# Generated by Django 5.0.6 on 2024-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_delete_propertybuildingmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_manager_iban',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
