# Generated by Django 5.0.6 on 2024-06-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_property_owner_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner_1',
        ),
    ]
