# Generated by Django 5.0.6 on 2024-06-05 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0013_landlord_law_firm'),
        ('properties', '0017_alter_property_owner_1_alter_property_owner_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='management_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_owner_2', to='landlords.landlord'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rg_ammount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='rg_ending',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rg_percentage',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='rg_starting',
            field=models.DateField(blank=True),
        ),
    ]
