# Generated by Django 5.0.6 on 2024-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_property_management_fee_alter_property_owner_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='utilisation_status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Vacant', 'Vacant'), ('Remove From Market', 'Remove From Market')], max_length=50, null=True),
        ),
    ]
