# Generated by Django 5.0.6 on 2024-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_property_utilisation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='utilisation_status',
            field=models.CharField(blank=True, choices=[('Rented', 'Rented'), ('Vacant', 'Vacant'), ('Remove From Market', 'Remove From Market')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
