# Generated by Django 5.0.6 on 2024-06-05 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0013_landlord_law_firm'),
        ('properties', '0020_alter_property_utilisation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_owner_1', to='landlords.landlord', unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_owner_2', to='landlords.landlord', unique=True),
        ),
    ]
