# Generated by Django 5.0.6 on 2024-06-08 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingManagementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_municipality', models.CharField(blank=True, max_length=50)),
                ('company_zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('designated_person_first_name', models.CharField(blank=True, max_length=50)),
                ('designated_person_last_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Building Management Companies',
            },
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_municipality', models.CharField(blank=True, max_length=50)),
                ('company_zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('company_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Electricity',
            },
        ),
        migrations.CreateModel(
            name='FurnitureProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_municipality', models.CharField(blank=True, max_length=50)),
                ('company_zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('company_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Furniture Providers',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_municipality', models.CharField(blank=True, max_length=50)),
                ('company_zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('company_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Legal',
            },
        ),
        migrations.CreateModel(
            name='NaturalGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_municipality', models.CharField(blank=True, max_length=50)),
                ('company_zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('company_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Natural Gas',
            },
        ),
        migrations.CreateModel(
            name='SubContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_municipality', models.CharField(blank=True, max_length=50)),
                ('company_zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('company_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sub-contractors',
            },
        ),
    ]
