# Generated by Django 5.0.6 on 2024-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, choices=[('K/P', 'Kp'), ('KMD', 'Kmd')], max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Legal',
            },
        ),
    ]
