# Generated by Django 5.0.6 on 2024-06-07 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_municipality', models.CharField(blank=True, max_length=50)),
                ('company_zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('company_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Furniture Providers',
            },
        ),
        migrations.CreateModel(
            name='SubContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(blank=True, max_length=50)),
                ('company_municipality', models.CharField(blank=True, max_length=50)),
                ('company_zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('company_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Subcontractors',
            },
        ),
    ]
