# Generated by Django 5.0.6 on 2024-06-07 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='company_municipality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legal',
            name='company_zip_code',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
            preserve_default=False,
        ),
    ]
