# Generated by Django 5.0.6 on 2024-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmanagementcompany',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='furnitureprovider',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
