# Generated by Django 5.0.6 on 2024-06-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_legal_company_municipality_legal_company_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
    ]
