# Generated by Django 5.0.6 on 2024-06-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0002_furnitureprovider_subcontractor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontractor',
            options={'verbose_name_plural': 'Sub-contractors'},
        ),
    ]
