# Generated by Django 5.0.6 on 2024-06-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0004_buildingmanagerindividual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingManagerIndividual',
            new_name='BuildingManagementCompany',
        ),
    ]
